include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Дополнительные правила для проекта
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false  # Разрешаем print для отладки
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    invalid_annotation_target: ignore
